# Generated by Django 5.1.1 on 2026-08-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="source",
            field=models.CharField(
                choices=[
                    ("markdown", "Markdown file"),
                    ("slack", "Slack message"),
                    ("manual", "Entered manually"),
                ],
                default="manual",
                max_length=50,
            ),
        ),
    ]
